### PR TITLE
Food Api

### LINKED ISSUE #10: Food Items Backend
A db with the following fields:

- foodId
- foodName
- dietType
- description
- specialIngredients
- serving
- specialNote
- foodImageId
- locationLat
- locationLong
- status:
- createdAt
- deletedAt
- updatedAt

The backend should allow for manipulation of the status field.

### PR DESCRIPTION
**Pull request by SammyOina**
build the database with parameters form the issues raised. Functioning and more to be added later

### CODE REVIEW

**Comment by rodneyosodo** [comment]
Linking issue #10

**Comment by rodneyosodo** [comment]
Do the godeps need to be added?

**Comment by rodneyosodo** [comment]
Also the vendor dir?

**Comment by SammyOina** [comment]
godeps will add automatically no need to add anything

**Comment by rodneyosodo** [comment]
It shouldn't be on git ignore?

**Comment by SammyOina** [comment]
go.mod file contains the dependencies for the program

**Comment by rodneyosodo** [comment]
And the deps folder?

**Comment by rodneyosodo** [comment]
Try building the file then run the executable

**Comment by rodneyosodo** [comment]
Src/Backend/UserApi/vendor/github.com are requirements?

**Comment by SammyOina** [comment]
the go.sum  has some deps which are downloaded and extracted in the docker file as go mod vendor ...

**Comment by rodneyosodo** [comment]
merging this one

**Pull request merged**
